import { DEFAULT_LORE_CONTROLS, type LoreEntry } from './lore.model';

export const testEntries: readonly LoreEntry[] = [
  {
    recordId: 'a',
    revision: 1,
    layerIds: [],
    sourceLayerId: undefined,
    sourceLayerWritePolicy: undefined,
    slug: 'a',
    title: 'Northmarch Taxes',
    summary: 'politics',
    body: 'The barons withheld taxes.',
    canonLevel: 'established',
    tags: ['politics'],
    loreControls: {
      ...DEFAULT_LORE_CONTROLS,
      primaryKeys: ['taxes'],
      constant: true,
      insertionOrder: 2,
    },
    capturedBy: 'test',
    captureReason: 'fixture',
    capturedAt: '2026-07-05T00:00:00.000Z',
    supersedesRecordId: '',
    supersededByRecordId: '',
  },
  {
    recordId: 'b',
    revision: 1,
    layerIds: [],
    sourceLayerId: undefined,
    sourceLayerWritePolicy: undefined,
    slug: 'b',
    title: 'Shadow Capital',
    summary: 'mystery',
    body: 'A hidden city.',
    canonLevel: 'speculative',
    tags: ['location'],
    loreControls: DEFAULT_LORE_CONTROLS,
    capturedBy: 'test',
    captureReason: 'fixture',
    capturedAt: '2026-07-05T00:00:00.000Z',
    supersedesRecordId: '',
    supersededByRecordId: '',
  },
];
